#line 1 "rcfile.cc"

#line 3 "rcfile.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer rcFlexLexer

#ifdef yyalloc
#define rcalloc_ALREADY_DEFINED
#else
#define yyalloc rcalloc
#endif

#ifdef yyrealloc
#define rcrealloc_ALREADY_DEFINED
#else
#define yyrealloc rcrealloc
#endif

#ifdef yyfree
#define rcfree_ALREADY_DEFINED
#else
#define yyfree rcfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[248] =
    {   0,
        0,    0,    0,    0,    2,    2,    0,    0,    0,    0,
        0,    0,   48,   46,   44,   45,   36,   46,   34,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   44,    4,    3,    2,   43,   43,   43,   43,
       41,   43,   37,   36,   46,   46,   35,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    4,    4,    3,    2,
        0,   42,   39,   41,    0,   37,   40,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   38,   40,    0,

        0,    9,    0,    0,    0,    0,    0,    0,    0,   21,
       23,    0,    0,    0,    0,    0,   31,    0,   20,    0,
        5,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   28,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   18,    0,
        0,    0,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   13,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   32,   33,    0,    0,    0,    0,
        0,    0,    0,    1,    0,    0,    0,   22,   24,   25,
        0,    0,    0,    0,    0,    0,   10,    0,   12,    0,

       14,    0,    0,    0,    0,    0,    0,    6,    0,    0,
        0,    0,    0,    0,    0,   29,    0,    0,    0,    0,
       11,    0,    0,    0,    0,    0,    0,    7,    0,    0,
        0,   16,    0,   30,   26,    0,    0,   15,   17,    8,
        0,    0,    0,    0,    0,   27,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    4,    4,    8,    4,
        4,    4,    9,    4,   10,    4,    4,   11,   11,   11,
       12,   11,   11,   11,   11,   11,   11,    4,    4,   13,
       14,   15,    4,    4,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        4,    4,    4,    4,   41,   42,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   25,   25,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    2,    3,    4,    4,    4,    4,    4,    4,    4,
        5,    5,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5
    } ;

static const flex_int16_t yy_base[255] =
    {   0,
        0,   65,    0,   66,   67,   71,   74,  116,   81,   92,
      100,  105,  505,  552,  552,  552,  552,  489,  552,   60,
       80,   84,   78,   85,   93,  105,  121,  121,  128,  142,
      110,  125,   93,    0,    0,  499,  552,  552,   94,    0,
        0,    0,  144,  178,  132,  127,  552,  145,  156,  141,
      149,  155,  145,  153,  153,  156,  162,  170,  166,  164,
      169,  166,  173,  181,  171,  136,    0,    0,    0,  498,
      203,  552,    0,    0,  491,  204,  175,  180,  189,  455,
      181,  200,  201,  210,  204,  207,  202,  202,  204,  454,
      208,  205,  205,  209,  212,  213,  230,  334,  552,  212,

      233,  254,  221,  220,  233,  242,  250,  248,  257,  552,
      552,  247,  259,  258,  262,  249,  552,  256,  552,  257,
      207,  252,  270,  265,  270,  265,  274,  268,  261,  277,
      288,  291,  275,  161,  286,  285,  285,  290,  308,  295,
      312,  301,  302,  312,  317,  322,  317,  321,  552,  314,
      312,  317,  330,  552,  330,  318,  334,  344,  334,  341,
      337,  343,  340,  372,  552,  357,  345,  111,  354,  362,
      363,  369,  361,  375,  552,  552,  361,  374,  371,  377,
      383,  380,  399,  552,  382,  381,  392,  552,  552,  552,
      374,  396,  396,  397,  405,  405,  552,  395,  552,  398,

      552,  406,  414,  418,  417,  423,  420,  552,  410,  429,
      426,  416,  426,  425,  426,  552,  424,  427,  427,  426,
      552,  108,  433,  426,  436,  450,  443,  552,  451,  444,
      443,  552,  462,  552,  552,  451,  456,  552,  552,  552,
      463,  466,  458,  473,  101,  552,  552,  520,  526,  532,
      538,  540,   80,  545
    } ;

static const flex_int16_t yy_def[255] =
    {   0,
      247,    1,    1,    1,  248,  248,  249,  249,    1,    1,
        1,    1,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  250,  251,  247,  247,  247,  247,  252,
      253,  254,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  250,  250,  251,  247,
      247,  247,  252,  253,  254,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  254,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,    0,  247,  247,  247,
      247,  247,  247,  247
    } ;

static const flex_int16_t yy_nxt[619] =
    {   0,
       14,   15,   16,   14,   17,   14,   14,   14,   14,   14,
       14,   14,   18,   19,   14,   20,   14,   14,   21,   14,
       14,   14,   22,   23,   14,   24,   25,   26,   14,   27,
       14,   28,   29,   30,   31,   32,   14,   14,   14,   14,
       14,   14,   20,   14,   14,   21,   14,   14,   14,   22,
       23,   24,   25,   26,   14,   27,   14,   28,   29,   30,
       31,   32,   14,   14,   14,   14,   33,   33,   36,   16,
       34,   34,   36,   16,   37,   38,   16,   37,   39,   37,
       40,   37,   37,   37,   74,   48,   37,   37,   37,   43,
       43,   43,   43,   33,   66,   71,   72,   34,   67,   49,

       43,   43,   43,   43,   44,   51,   33,   50,   53,   44,
       34,   48,  246,   52,   37,   42,   37,   38,   16,   37,
       39,   37,   40,   37,   37,   37,   49,   45,   37,   37,
       37,   51,   45,   54,   50,   53,   55,   66,   46,   52,
       58,   67,   64,   46,   65,   59,   78,   60,  230,   56,
       61,  187,   57,   45,   76,   76,   37,   42,   45,   54,
       77,   62,   82,   55,   46,   63,   83,   58,   64,   46,
       79,   65,   59,   78,   60,   56,   84,   61,   57,   71,
       72,   80,   85,   81,   86,   87,   77,   88,   62,   82,
       89,   90,   63,   83,   91,   92,   79,   93,   94,   95,

       96,  153,   97,   84,   71,   72,   86,   80,   85,   81,
       86,   87,   99,   88,   76,   76,   89,  100,   90,  102,
       91,   92,  103,   93,   94,   95,  104,   96,   97,  107,
      105,  118,   86,  109,  110,  111,  108,  112,   99,  114,
      115,  116,  117,  100,  119,  102,  120,  139,  121,  103,
      106,  122,  104,  124,  125,  107,  126,  105,  118,  109,
      110,  111,  108,  112,  127,  114,  115,  116,  117,  128,
      119,  129,  130,  120,  121,  131,  132,  134,  122,  124,
      125,  135,  143,  126,  137,  138,  140,  141,  144,  136,
      145,  127,  133,  146,  123,  147,  128,  142,  129,  130,

      148,  131,  149,  132,  134,  150,  151,  155,  135,  143,
      137,  138,  140,  152,  141,  144,  145,  154,  133,  156,
      146,  147,  157,  142,  160,  158,  148,  161,  149,  162,
      163,  164,  150,  151,  155,  159,  165,  166,  167,  152,
      168,   98,  169,  154,  170,  156,  171,  172,  157,  174,
      160,  175,  158,  176,  161,  162,  163,  173,  164,  177,
      181,  159,  178,  165,  166,  167,  179,  168,  169,  180,
      170,  182,  171,  183,  172,  185,  174,  175,  186,  188,
      176,  189,  190,  173,  191,  184,  177,  181,  178,  192,
      193,  195,  179,  194,  196,  180,  197,  182,  198,  199,

      183,  200,  185,  201,  186,  188,  205,  202,  189,  190,
      203,  191,  184,  206,  207,  192,  208,  193,  195,  194,
      209,  196,  210,  197,  204,  198,  199,  211,  200,  212,
      201,  213,  205,  214,  202,  215,  216,  203,  217,  218,
      206,  207,  219,  208,  220,  221,  228,  209,  222,  210,
      204,  223,  224,  211,  225,  212,  226,  213,  227,  229,
      214,  231,  215,  216,  232,  217,  218,  233,  219,  234,
      236,  220,  221,  228,  222,  235,  237,  223,  224,  238,
      225,  239,  226,  240,  227,  229,  241,  231,  242,  243,
      232,  244,  245,  233,  113,  101,  234,  236,   98,   70,

       70,  235,  237,   47,  247,  238,  247,  247,  239,  240,
      247,  247,  241,  247,  242,  247,  243,  244,  247,  245,
       35,   35,   35,   35,   35,   35,   41,   41,   41,   41,
       41,   41,   68,   68,  247,   68,   68,   68,   69,  247,
      247,   69,   69,   69,   73,   73,   75,  247,   75,   75,
       75,   13,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247
    } ;

static const flex_int16_t yy_chk[619] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    4,    5,    5,
        2,    4,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,  253,   20,    7,    7,    7,    9,
        9,    9,    9,   10,   33,   39,   39,   10,   33,   21,

       10,   10,   10,   10,   11,   23,   12,   22,   25,   12,
       12,   20,  245,   24,    7,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   21,   11,    8,    8,
        8,   23,   12,   26,   22,   25,   27,   66,   11,   24,
       28,   66,   31,   12,   32,   29,   46,   29,  222,   27,
       29,  168,   27,   11,   43,   43,    8,    8,   12,   26,
       45,   30,   50,   27,   11,   30,   51,   28,   31,   12,
       48,   32,   29,   46,   29,   27,   52,   29,   27,   44,
       44,   49,   53,   49,   54,   55,   45,   56,   30,   50,
       57,   58,   30,   51,   59,   60,   48,   61,   62,   63,

       64,  134,   65,   52,   71,   71,   77,   49,   53,   49,
       54,   55,   78,   56,   76,   76,   57,   79,   58,   81,
       59,   60,   82,   61,   62,   63,   83,   64,   65,   85,
       84,   95,   77,   86,   87,   88,   85,   89,   78,   91,
       92,   93,   94,   79,   96,   81,   97,  121,  100,   82,
       84,  101,   83,  103,  104,   85,  105,   84,   95,   86,
       87,   88,   85,   89,  106,   91,   92,   93,   94,  107,
       96,  108,  109,   97,  100,  112,  113,  114,  101,  103,
      104,  115,  124,  105,  118,  120,  122,  123,  125,  116,
      126,  106,  113,  127,  102,  128,  107,  123,  108,  109,

      129,  112,  130,  113,  114,  131,  132,  136,  115,  124,
      118,  120,  122,  133,  123,  125,  126,  135,  113,  137,
      127,  128,  138,  123,  140,  139,  129,  141,  130,  142,
      143,  144,  131,  132,  136,  139,  145,  146,  147,  133,
      148,   98,  150,  135,  151,  137,  152,  153,  138,  155,
      140,  156,  139,  157,  141,  142,  143,  153,  144,  158,
      162,  139,  159,  145,  146,  147,  160,  148,  150,  161,
      151,  163,  152,  164,  153,  166,  155,  156,  167,  169,
      157,  170,  171,  153,  172,  164,  158,  162,  159,  173,
      174,  178,  160,  177,  179,  161,  180,  163,  181,  182,

      183,  185,  166,  186,  167,  169,  191,  187,  170,  171,
      187,  172,  183,  192,  193,  173,  194,  174,  178,  177,
      195,  179,  196,  180,  187,  181,  182,  198,  185,  200,
      186,  202,  191,  203,  187,  204,  205,  187,  206,  207,
      192,  193,  209,  194,  210,  211,  219,  195,  212,  196,
      187,  213,  214,  198,  215,  200,  217,  202,  218,  220,
      203,  223,  204,  205,  224,  206,  207,  225,  209,  226,
      229,  210,  211,  219,  212,  227,  230,  213,  214,  231,
      215,  233,  217,  236,  218,  220,  237,  223,  241,  242,
      224,  243,  244,  225,   90,   80,  226,  229,   75,   70,

       36,  227,  230,   18,   13,  231,    0,    0,  233,  236,
        0,    0,  237,    0,  241,    0,  242,  243,    0,  244,
      248,  248,  248,  248,  248,  248,  249,  249,  249,  249,
      249,  249,  250,  250,    0,  250,  250,  250,  251,    0,
        0,  251,  251,  251,  252,  252,  254,    0,  254,  254,
      254,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "rcfile.ll"
/* *********************************************************************** */
/* A scanner definition for Mailfilter's config files                      */
/* Copyright (c) 2000 - 2009  Andreas Bauer <baueran@gmail.com>            */
/*                                                                         */
/* This program is free software; you can redistribute it and/or modify    */
/* it under the terms of the GNU General Public License as published by    */
/* the Free Software Foundation; either version 2 of the License, or       */
/* (at your option) any later version.                                     */
/*                                                                         */
/* This program is distributed in the hope that it will be useful,         */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of          */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           */
/* GNU General Public License for more details.                            */
/*                                                                         */
/* You should have received a copy of the GNU General Public License       */
/* along with this program; if not, write to the Free Software             */
/* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,   */
/* USA.                                                                    */
/* *********************************************************************** */
/* The states are numbered from 1...n and are stored in YY_START.  */





#line 30 "rcfile.ll"
#include <fstream>
#include <iostream>
#include <string>
#include <cstdlib>
#include <cstring>
#include <cstdio>

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "rcparser.hh"

extern "C"
{
#include <wordexp.h>
}

using namespace std;

/* Only allow 'recursion depth' of 1 when including files.  */
#define MAX_INCLUDE_DEPTH   1

/* Define L_DEBUG_MODE to get extra output from the scanner.  */
#ifdef L_DEBUG_MODE
#undef L_DEBUG_MSG
#define L_DEBUG_MSG(msg)    \
   cout << "Lexer: "        \
        << msg              \
        << endl
#else
#define L_DEBUG_MSG(msg)    \
   ;
#endif

YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int             include_stack_ptr;

extern string expand_path (const string&);
extern string int_to_string (int val);
#line 700 "rcfile.cc"
#line 113 "rcfile.ll"
		int    num_lines      = 0;
		int    temp_num_lines = 0;
		string sub_file;
#line 705 "rcfile.cc"

#define INITIAL 0
#define CTRL 1
#define INCL 2
#define PARAM 3
#define PARAM_NUM 4
#define PARAM_BOOL 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 117 "rcfile.ll"

#line 847 "rcfile.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 248 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 552 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "rcfile.ll"
{
     BEGIN(INCL);
     temp_num_lines = num_lines;
     num_lines = 0;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 124 "rcfile.ll"
{; /* Eat the whitespace.  */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 126 "rcfile.ll"
{
     /* Include further rcfiles:  */
     wordexp_t result;

     if (include_stack_ptr >= MAX_INCLUDE_DEPTH)
     {
        cerr << PACKAGE_NAME << ": Error: Files nested too deep." << endl;
	exit (-1);
     }
     include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
     
     try
     {
        if (wordexp (yytext, &result, 0) == 0)
        {
	   sub_file = result.we_wordv[0];
           wordfree (&result);
        }
        else
        {
           cerr << PACKAGE_NAME << ": Error: Nested rcfile '";
	   cerr << yytext << "' could not be found." << endl;
	   exit (-1);
        }
	
	// yyin is now a std::istream& it seems. So the following no longer works:
	// yyin = new ifstream (sub_file.c_str ());
	std::ifstream* infile = new ifstream (sub_file.c_str ());

	// if (!((std::ifstream*) yyin)->is_open ())
        if (!infile->is_open ())
        {
           cerr << PACKAGE_NAME << ": Error: Nested rcfile '";
	   cerr << sub_file << "' could not be opened." << endl;
	   exit (-1);
        }

        yy_switch_to_buffer (yy_create_buffer (infile, YY_BUF_SIZE));
	// yy_switch_to_buffer (yy_create_buffer (yyin, YY_BUF_SIZE));
     }
     catch (...)
     {
	cerr << PACKAGE_NAME << ": Error: Exception was thrown when "
	     << "trying to read '"
             << yytext << "'." << endl;
        exit (-1);
     }

     BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CTRL):
case YY_STATE_EOF(INCL):
case YY_STATE_EOF(PARAM):
case YY_STATE_EOF(PARAM_NUM):
case YY_STATE_EOF(PARAM_BOOL):
#line 177 "rcfile.ll"
{
     if (--include_stack_ptr < 0)
        yyterminate ();
     else
     {
        yy_delete_buffer (YY_CURRENT_BUFFER);
        yy_switch_to_buffer (include_stack[include_stack_ptr]);
     }

     num_lines = temp_num_lines;
     sub_file = "";
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 190 "rcfile.ll"
{; /* Do nothing with remarks.  */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 192 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Allow.");
     return ALLOW;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 198 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Allow_Case.");
     return ALLOW_CASE;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 204 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Allow_Nocase.");
     return ALLOW_NOCASE;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 210 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Del_Duplicates.");
     BEGIN(PARAM_BOOL);
     return DEL_DUPLICATES;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 217 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Deny.");
     return DENY;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 223 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Deny_Case.");
     return DENY_CASE;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 229 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Deny_Nocase.");
     return DENY_NOCASE;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 235 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Highscore.");
     BEGIN(PARAM_NUM);
     return HIGHSCORE;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 242 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Logfile.");
     return LOGFILE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 248 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Maxlength.");
     BEGIN(PARAM_NUM);
     return MAXLENGTH;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 255 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Maxsize_Allow.");
     BEGIN(PARAM_NUM);
     return MAXSIZE_ALLOW;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 262 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Maxsize_Deny.");
     BEGIN(PARAM_NUM);
     return MAXSIZE_DENY;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 269 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Maxsize_Score.");
     BEGIN(PARAM_NUM);
     return MAXSIZE_SCORE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 276 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Normal.");
     BEGIN(PARAM_BOOL);
     return NORMAL;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 283 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Server.");
     return SERVER;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 289 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("User.");
     return USER;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 295 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Pass.");
     return PASS;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 301 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Protocol.");
     return PROTOCOL;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 307 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Port.");
     BEGIN(PARAM_NUM);
     return PORT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 314 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Reg_Case.");
     BEGIN(PARAM_BOOL);
     return REG_CASE;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 321 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Reg_Type.");
     return REG_TYPE;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 327 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Show_Headers.");
     return SHOW_HEADERS;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 333 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Log_Headers_SQLite3.");
     return LOG_HEADERS_SQLITE3;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 339 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Score.");
     BEGIN(PARAM_NUM);
     return SCORE;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 346 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Score_Case.");
     BEGIN(PARAM_NUM);
     return SCORE_CASE;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 353 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Score_Nocase.");
     BEGIN(PARAM_NUM);
     return SCORE_NOCASE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 360 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Test.");
     BEGIN(PARAM_BOOL);
     return TEST;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 367 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Timeout.");
     BEGIN(PARAM_NUM);
     return TIMEOUT;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 374 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Verbose.");
     BEGIN(PARAM_NUM);
     return VERBOSE;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 381 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG((string)rclval.sval +
          " (" + int_to_string (YY_START) + ")");
     return '=';
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 388 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG((string)rclval.sval +
	         " (" + int_to_string (YY_START) + ")");
     return NOT_EQUAL;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 395 "rcfile.ll"
{
     /* Beginning of an argument:  */
     rclval.sval = strdup (yytext);
     if (YY_START != PARAM_BOOL)
       BEGIN(PARAM);
     L_DEBUG_MSG((string)"Opening \"" +
	         " (" + int_to_string (YY_START) + ")");
     return '"';
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 405 "rcfile.ll"
{
     rclval.ival = atoi (yytext);
     L_DEBUG_MSG("Num_Id: " + (string)yytext +
	         " (" + int_to_string (YY_START) + ")");
     return NUM_ID;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 412 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Shell_Cmd: " + (string)rclval.sval +
	         " (" + int_to_string (YY_START) + ")");
     return SHELL_CMD;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 419 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Env_Var: " + (string)rclval.sval +
	         " (" + int_to_string (YY_START) + ")");
     return ENV_VAR;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 426 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Yes_No_Id: " + (string)rclval.sval + 
	         " (" + int_to_string (YY_START) + ")");
     return YES_NO_ID;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 433 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Text_Id: " + (string)rclval.sval +
                 " (" + int_to_string (YY_START) + ")");
     return TEXT_ID;
}
	YY_BREAK
case 42:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 440 "rcfile.ll"
{
     /* Ending of an argument:  */
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG((string)"Closing \"" +
	         " (" + int_to_string (YY_START) + ")");
     return '"';
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 448 "rcfile.ll"
{
     rclval.sval = strdup (yytext);
     L_DEBUG_MSG("Ctrl_Char: " + (string)rclval.sval +
	         " (" + int_to_string (YY_START) + ")");
     return CTRL_CHAR;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 455 "rcfile.ll"
{; /* Do nothing with tabs and spaces.  */ }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 457 "rcfile.ll"
{ ++num_lines; BEGIN(0); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 459 "rcfile.ll"
{
     if (sub_file != "")
     {
     	cerr << PACKAGE_NAME << ": Error: Lexicographical error in line ";
        cerr << (num_lines + 1) << " of your rcfile '" << sub_file;
        cerr << "'."  << endl;
     }
     else
     {
        cerr << PACKAGE_NAME << ": Error: Lexicographical error in line ";
        cerr << (num_lines + 1) << " of your main rcfile."  << endl;
     }

     cerr << PACKAGE_NAME << ": The term '" << yytext;
     cerr << "' could not be interpreted." << endl;
     exit (-1);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 477 "rcfile.ll"
ECHO;
	YY_BREAK
#line 1418 "rcfile.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 248 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 248 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 247);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 477 "rcfile.ll"


